matzipback/src/main/resources/application.yml

🌟개요
---
application.yml 설정 파일 수정
🌐연결된 Issues
---
#50 
📋작업사항
---
- ddl-auto: none 설정
- mapper-locations 수정해서 이제 resourse/mappers/ 하위에서 만든 mapper를 모두 인식함
✅체크리스트
---

chore: ddl-auto, mapper-locations 수정

---

matzipback/src/main/resources/application.yml

🌟개요
---
.env 파일을 인식시키는 설정 추가
🌐연결된 Issues
---
#53 
📋작업사항
---
application.yml 에서 .env 파일을 찾게하는 설정 추가
✅체크리스트
---

fix: .env 파일 인식하는 설정 추가

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Restaurant.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Review.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/ReviewImage.java

🌟개요
aggregate 하위 엔티티 파일 추가
🌐연결된 Issues
---
📋작업사항
MyList
MyListComment
MyListMayzip
Restaurant
Review
ReviewImage 파일 추가
MyList의 경우 List라는 클래스 명이 오류를 발생시킬 위험이 있어 MyList로 지정했습니다.
---
✅체크리스트
---

feat: list/domain/command/aggregate 파일 추가

---

matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/BoardCategoryDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/BoardMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/BoardQueryService.java
matzipback/src/main/resources/mappers/boardMappers/BoardMapper.xml

🌟개요
---
게시판 카테고리 전체 조회 기능 구현
🌐연결된 Issues
---
#52 
📋작업사항
---
게시판 카테고리 전체 조회 기능 구현을 위한 Controller, DTO, Mapper, Mapper.xml, Service 추가
✅체크리스트
---

feat: 게시판 카테고리 전체 조회 기능 구현

---

matzipback/src/test/java/com/matzip/matzipback/board/query/service/BoardQueryServiceTest.java

🌟개요
---
게시판 전체 목록 조회 Test code 구현
🌐연결된 Issues
---
#60 
📋작업사항
---
- 조회한 게시판 카테고리 목록이 null 이 아닌지 체크
- 조회한 게시판 카테고리 목록이 사이즈가 0이상인지 체크
- 조회한 게시판 카테고리가 실제로 맞는 값이 들어가 있는지 체크
✅체크리스트
---

test: 게시판 전체 목록 조회 Test code 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/BoardMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/BoardQueryService.java
matzipback/src/main/resources/mappers/boardMappers/BoardMapper.xml

🌟개요
---
게시판 즐겨찾기 목록 조회 기능 구현
🌐연결된 Issues
---
#59 
📋작업사항
---
게시판 즐겨찾기 목록 조회 관련 Controller, Service, Repository, Mapper  구현
✅체크리스트
---

feat: 게시판 즐겨찾기 목록 조회 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportCommandContoller.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportCommandService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Reason.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/service/ReportInfraService.java
matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandContoller.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/BusinessLicense.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserStatus.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UsersDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/service/UsersInfraService.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersQueryService.java

🌟개요
---
Entity 생성
🌐연결된 Issues
---
#88 
#89 
📋작업사항
---
---
✅체크리스트
---

회원관리 및 신고쪽 Entity 및 파일 생성

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Restaurant.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/Review.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/ReviewImage.java

🌟개요
시퀀스 자료형 변경
🌐연결된 Issues
---
📋작업사항
시퀀스의 자료형을 int -> long으로 변경
---
✅체크리스트
---

chore: 시퀀스 타입 변경 int -> long

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/RequestPostCommentDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResponsePostCommentDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostCommentRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostCommentDomainService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostCommentInfraRepository.java

🌟개요
---
게시글 댓글 작성 기능 구현
🌐연결된 Issues
---
#97
📋작업사항
---
게시판 PostComment Entity 수정
---
✅체크리스트
---

feat: 게시글 댓글 작성 기능 구현

---

matzipback/build.gradle
matzipback/src/main/java/com/matzip/matzipback/config/AppConfig.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/HMACKeyGenerator.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/ExceptionResponseDTO.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/LoginRequestDTO.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/filter/CustomAuthenticationFilter.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/filter/JwtFilter.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/JwtAccessDeniedHandler.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/JwtAuthenticationEntryPoint.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginFailureHandler.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/handler/LoginSuccessHandler.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/JwtUtil.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandContoller.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateUserRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersInfraRepository.java
matzipback/src/main/resources/application.yml

🌟개요
---
회원 가입, 로그인 구현
🌐연결된 Issues
---
#62 , #70 
📋작업사항
---
- 회원 가입 로직 구현
- 로그인 로직 구현
- SpringConfig 추가
- 로그인 필터 추가
- JWT 토큰 발급
- 토큰 유효성 검사
✅체크리스트
---

feat : 회원가입, 로그인 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtCreateDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtCreateDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java

🌟개요
---
작성한 게시물에 댓글을 수정하는 기능
🌐연결된 Issues
---
#101 
📋작업사항
---
게시물 댓글 수정 기능 구현
---
요청, 응답 DTO 수정
응답 DTO 통합
✅체크리스트
---

feat: 게시물 댓글 수정 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Reason.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/ActiveLevel.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/BusinessLicense.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Follow.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/MessageBlock.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Messages.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java

🌟개요
회원관리 및 신고 엔티티 생성 및 데이터타입 변경
🌐연결된 Issues
#88 #89 
📋작업사항
데이터 타입 int -> Long
,엔티티 생성
---
✅체크리스트
---

회원, 신고 엔티티 생성 및 데이터타입 변경

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtDeleteDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java

🌟개요
---
작성된 게시물의 댓글을 삭제하는 기능
🌐연결된 Issues
---
#107 
📋작업사항
---
게시물 댓글 삭제 기능 구현
---
삭제 요청 DTO 생성
PostComment 엔티티 소프트 삭제 쿼리문 수정
✅체크리스트
---

feat: 게시물 댓글 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostImage.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostTag.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Tag.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDto.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostListResponse.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml

🌟개요
---
검색조건(게시글 제목, 게시글 작성자 닉네임)에 부합하는 게시글을 검색하는 기능
🌐연결된 Issues
---
#103 
📋작업사항
---
게시글 검색 기능 구현
---
게시판 Entity 수정 (seq 타입 : int -> LONG)
✅체크리스트
---

feat: 게시글 검색 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/MatzipbackApplication.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
matzipback/src/main/java/com/matzip/matzipback/config/ModelMapperConfig.java
matzipback/src/main/resources/application.yml

🌟개요
---
댓글 관련 기능 End Point URI 수정
PostComment 시간 관련 annotation 미작동으로 인해 prePersist 메서드로 수정
ModelMapperConfig 생성
🌐연결된 Issues
---
#101 
📋작업사항
---
PostComment  Entity 시간 관련 annotation에 필요한 Auditing 활성화 및 필드 설정
---
ModelMapperConfig 생성
application.yml 내 username: 오타 수정
✅체크리스트
---

chore: 댓글 관련 기능 수정

---

matzipback/src/main/java/com/matzip/matzipback/common/util/CustomUserUtils.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/JwtUtil.java

🌟개요
---
Authetication에서 userDetails의 userSeq 가져오는 기능 추가
🌐연결된 Issues
---
#114 
📋작업사항
---
- 커스텀 util 클래스 추가
- 커스텀 util 클래스는 Authentication에서 userSeq를 가져옴
---
- swagger url 허용하는 설정 SecurityConfig에 추가
✅체크리스트
---

feat: userDeatils에서 사용자 정보 가져오는 공통 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ApplicationListController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateListRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ApplicationListService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/DomainListRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraListRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/ListMapper.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListCategoryDTO.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandControllerTest.java

🌟개요
리스트 생성 기능 구현
🌐연결된 Issues
#23 리스트 생성
📋작업사항
맛집 리스트 생성 기능 구현
---
✅체크리스트
---

feat: #23 리스트 생성 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/LikeCommandController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/LikeCommandService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/aggregate/Like.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/LikeDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostCmtLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/LikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostCmtLikeInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/query/mapper/LikeQueryMapper.java
matzipback/src/main/java/com/matzip/matzipback/like/query/service/LikeQueryService.java
matzipback/src/main/resources/mappers/likeMappers/LikeQueryMapper.xml

🌟개요
---
게시물 댓글을 좋아요하거나 취소할 수 있는 기능
🌐연결된 Issues
---
#120 
📋작업사항
---
Like Entity
Like command, query 패키지 구분 생성
PostCmtLike Controller, Service, Repository, Mapper 생성
게시물 댓글 좋아요/좋아요 취소 기능 구현
Mapper.xml 생성 및 조회 쿼리문 추가
---
✅체크리스트
---

Feat: 게시물 댓글 좋아요/좋아요 취소 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommentController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java

🌟개요
---
게시글 댓글 삭제 요청 받는 방식 수정
🌐연결된 Issues
---
#107 
📋작업사항
---
요청 방식 수정
응답 반환형 수정
---
✅체크리스트
---

chore: 게시글 댓글 삭제 기능 요청 방법 수정 및 응답 반환형 수정

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/PostRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java

🌟개요
---
게시글 Soft Delete 기능
🌐연결된 Issues
---
#117
📋작업사항
---
게시글 삭제 기능 구현
---
게시글 검색, 게시글 목록 조회 URL 수정
✅체크리스트
---

feat: 게시글 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java

🌟개요
리스트 생성 테스트 코드로 변경
🌐연결된 Issues
#23 리스트 생성 기능 구현
📋작업사항
유저 시퀀스 테스트 코드로 변경
---
✅체크리스트
---

fix: #23 리스트 생성 테스트 코드로 변경

---

matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCmtListResponseDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostCmtMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml

🌟개요
---
회원 본이이 작성한 댓글들 조회하는 기능 구현
🌐연결된 Issues
---
#132 
📋작업사항
---
DTO, Controller, Service, Mapper 생성
기능 구현에 맞는 쿼리문 작성
---
✅체크리스트
---

feat: 회원 본인이 작성한 댓글들 조회하는 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml

🌟개요
---
로직을 간결하게 하기 위해 쿼리문 수정 및 로직 수정
🌐연결된 Issues
---
#132 
📋작업사항
---
서비스 로직 간결화
댓글 매퍼 내 쿼리문 수정
---
✅체크리스트
---

chore: 회원 본인이 작성한 게시글 댓글 조회 서비스 로직, 쿼리문 수정

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java

🌟개요
리스트 삭제 기능 구현
🌐연결된 Issues
#24 리스트 삭제
📋작업사항
리스트 삭제 기능을 소프트 삭제로 구현했습니다.
✅체크리스트
---

feat: #24 리스트 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeResMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/aggregate/Like.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostLikeInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActivityRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UserActivityInfraRepository.java

🌟개요
---
게시글 기능 추가
🌐연결된 Issues
---
#130 
📋작업사항
---
- 게시글 좋아요 기능 추가
- 활동 점수 상태 변화 메서드 추가
✅체크리스트
---

feat: 게시글 좋아요 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListCategoryDTO.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListContentDTO.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/MatzipDTO.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml

🌟개요
리스트 상세 조회 기능 구현
🌐연결된 Issues
#22 리스트 상세 조회
📋작업사항
리스트 상세 조회 기능 구현
음식점, 좋아요, 맛집 DB에 데이터 넣어서  테스트 했었습니다.
✅체크리스트
---

feat: #22 리스트 상세조회 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCmtListResponseDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostCmtMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostCmtQueryService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostResMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/query/mapper/LikeQueryMapper.java
matzipback/src/main/java/com/matzip/matzipback/like/query/service/LikeQueryService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchUserDTO.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml
matzipback/src/main/resources/mappers/likeMappers/LikeQueryMapper.xml
matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml

🌟개요
---
게시글 좋아요 등록, 취소 기능에서 구현 방식 변경
🌐연결된 Issues
---
#141 
📋작업사항
---
- 기존 entity 내에 메서드를 만들어서 entity로 바꾸는 과정을 없앤다.
- modelMapper 를 사용해서 entity 로 변경하는 구현 방식을 이용함
✅체크리스트
---

refactoring: 게시글 좋아요 등록, 취소 기능에서 구현 방식 변경

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java

🌟개요
---
충돌 해결하면서 잘못 지워진 메서드 다시 추가
🌐연결된 Issues
---
#150 
📋작업사항
---
잘못 지워진 메서드 추가함
✅체크리스트
---

chore: 충돌 해결하면서 지워진 메서드 추가

---

matzipback/build.gradle
matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/EmailController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/EmailService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersCommandService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/utility/UUIDGenerator.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateSocialRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateUserRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailChkRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
matzipback/src/main/resources/application.yml

🌟개요
회원 가입 기능 추가
🌐연결된 Issues
#62 
#66 
#67 
📋작업사항
유효값 검증, 이메일 중복체크, 닉네임 중복체크, 이메일 인증, 임의 닉네임 생성 구현 완료
---
✅체크리스트
---

회원가입 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/responsemessage/ResponseMessage.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersFollowController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/UsersFollowService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Follow.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/FollowId.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersFollowRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UsersFollowDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/FollowDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/FollowResMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersFollowInfraRepository.java

🌟개요
---
팔로우 등록, 취소 기능 구현
🌐연결된 Issues
---
#152 
📋작업사항
---
- 팔로우 관계에서는 팔로우를 누를 시 팔로우 취소됨
- 팔로우 관계가 아니면 팔로우 누르면 팔로우가 됨
- 팔로우 응답을 위한 ReponseMessage enum에 메시지 추가함
✅체크리스트
---

feat: 팔로우 등록, 취소 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/restaurant/command/aggregate/Restaurant.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantDetailResponse.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantDto.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/dto/RestaurantListResponse.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/mapper/RestaurantMapper.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/service/RestaurantQueryService.java
matzipback/src/main/resources/mappers/restaurantMappers/RestaurantMapper.xml

🌟개요
---
음식점 검색, 음식점 상세조회 기능 추가
🌐연결된 Issues
---
#44 #45 #47 
📋작업사항
---
restaurantdto 이동
restaurant 하위 코드 작업
---
✅체크리스트
---

feat: 음식점 검색, 음식점 상세조회 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersFollowQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/FollowQueryResMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/FollowingUsersDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersFollowMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersFollowQueryService.java
matzipback/src/main/resources/mappers/followMappers/UsersFollowMappers.xml

🌟개요
---
내가 팔로우를 보낸 유저들의 목록을 조회한다.
🌐연결된 Issues
---
#154 
📋작업사항
---
- 내가 팔로우한 회원의 닉네임을 보여주는 기능을 구현함
✅체크리스트
---

feat: 팔로잉 목록 조회

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateListCmtRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraListCmtDomainRespository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/ListCmtMapper.java

🌟개요
리스트 댓글 작성 기능 구현
🌐연결된 Issues
#33 
📋작업사항
listSeq, listCommentContent 를 받아서 댓글 등록이 완료되게 하였습니다. 
---
✅체크리스트
---

feat: #33 리스트 댓글 작성 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeMessageReqDto.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/ListLikeInfraRepository.java

🌟개요
리스트 좋아요 등록 기능 구현
🌐연결된 Issues
#37 
📋작업사항
리스트 유저 시퀀스, 리스트 시퀀스를 이용해서 리스트 좋아요 등록 기능을 구현했습니다.
---
✅체크리스트
---

feat: #37 리스트 좋아요 등록 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/CreateMatzipRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListMatzip.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/MatzipDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/infrastructure/repository/InfraMatzipRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/mapper/MatzipMapper.java

🌟개요
리스트 내 맛집 등록 기능 구현
🌐연결된 Issues
#27 
📋작업사항
맛집 등록 기능 구현하고 테스트 완료하였습니다.
list Command Controller 파일 주석 정리
✅체크리스트
---

feat: #27 리스트 내 맛집 등록 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/ActiveLevel.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/UserActivity.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActiveLevelDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/infrastructure/repository/UsersActiveLevelInfraRepository.java

🌟개요
---
회원 등급 자동 변경 기능 구현
🌐연결된 Issues
---
#167 
📋작업사항
---
- 회원에 활동에 따른 점수가 업데이트 될 때 등급을 계산하는 로직 추가
---
✅체크리스트
---

feat: 회원 등급 자동 변경 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java

🌟개요
리스트 업데이트 기능 구현
🌐연결된 Issues
#25 리스트 수정
📋작업사항
리스트 업데이트 model mapper 이용해서 구현
---
✅체크리스트
---

Feat: #25 리스트 업데이트 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteMatzipRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/MatzipDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainMatzipService.java

🌟개요
리스트 맛집 삭제 기능 구현
🌐연결된 Issues
---
📋작업사항
소프트 삭제로 기능 구현하였습니다.
딸려온 커밋 로그 때문에 
먼저 올라온 pr부터 봐주시면 감사하겠습니다!
---
✅체크리스트
---

feat: #25 리스트 맛집 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/users/query/controller/ActiveLevelQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/ActiveLevelDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/ActiveLevelResMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/ActiveLevelMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/ActiveLevelQueryService.java
matzipback/src/main/resources/mappers/ActiveLevelMappers/ActiveLevelMapper.xml

🌟개요
---
활동 등급 전체 조회 구현 (관리자 기능)
🌐연결된 Issues
---
#170 
📋작업사항
---
- 활동 등급 전체 조회 구현
- 페이징 처리를 추가함
✅체크리스트
---

feat: 활동 등급 전체 조회 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ResPostCmtDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java

🌟개요
---
댓글 작성, 수정, 삭제 기능 중 응답 시 처리 성공, 실패 코드 및 메세지 전송하도록 리팩토링
🌐연결된 Issues
---
#113 
#123 
#148 
📋작업사항
---
Controller, Service 에서 if문 추가하여 처리 성공 및 실패 시 따로 리턴 값 전송하도록 수정
게시글 댓글 수정 요청 DTO에 postSeq 필드 추가
---
✅체크리스트
---

refactor: 댓글 관련 기능 리팩토링

---

matzipback/src/main/java/com/matzip/matzipback/config/SwaggerConfig.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UsersDomainRepository.java

🌟개요
---
스웨거 인증 기능 활성화
스웨거 내에서 헤더를 포함해서 요청을 보내는 것 까지는 됐고 추가로 개선해야 할 점이 있지만 일단 가능은 해서 임시로 올립니다.
🌐연결된 Issues
---
#195
📋작업사항
---
[feat: 스웨거 인증 기능 활성화](https://github.com/taste-house/mat_zip/commit/ae41a6e309ab6c0d96210d6d4aba05042c7e3d28)
[fix: 임시로 토큰-검증의 email-seq 불일치 해소](https://github.com/taste-house/mat_zip/commit/96baeebaf2d75bc4eb4984f1a14d2978dd2d2a40)
---
✅체크리스트
---

feat: 스웨거 인증 기능 활성화

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListCmtRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java

🌟개요
리스트 댓글 삭제 기능 구현
🌐연결된 Issues
#34 리스트 댓글 삭제
📋작업사항
---
리스트 댓글 삭제 기능 소프트 삭제 구현하였습니다.
✅체크리스트
---

feat: #34 리스트 댓글 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeMessageReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java

🌟개요
리스트 좋아요 등록/취소 기능 파일명 및 코드 수정
🌐연결된 Issues
#201 
📋작업사항
파일명, 코드 수정, valid, NotNull 추가
---
✅체크리스트
---

chore: #201 리스트 좋아요 등록/취소 기능 파일명 및 코드 수정

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java

🌟개요
리스트 업데이트 기능 로직 수정
🌐연결된 Issues
📋작업사항
리스트 업데이트 기능 엔티티에 setter 달아서 구현했던 로직을 setter를 제거하여 다른 방식으로 구현
---
✅체크리스트
---

fix: #199 리스트 업데이트 기능 로직 수정

---

matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/ActiveLevelResDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelRequestDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/CreateActiveLevelResMessageDTO.java

🌟개요
---
활동 등급을 추가하는 기능 구현
🌐연결된 Issues
---
#172 
📋작업사항
---
- 활동 등급을 추가하는 기능 구현
- 이는 관리자의 기능임
✅체크리스트
---

feat: 활동 등급을 추가하는 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListCmtRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListCmtDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListCmtUpdateService.java

🌟개요
리스트 댓글 수정 기능 구현
🌐연결된 Issues
#35 
📋작업사항
리스트 댓글 수정 로직 추가
---
✅체크리스트
---

feat: #35 리스트 댓글 수정 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportListService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ListDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ListDomainService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqMessageDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ListInfraRepository.java

🌟개요
리스트 신고 기능 구현
🌐연결된 Issues
#26 
📋작업사항
리스트 신고 기능 동작 로직 추가
---
✅체크리스트
---

feat: 리스트 신고 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/exception/NotFoundException.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/conroller/RestaurantCommandController.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/controller/RestaurantCommandController.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/dto/RestaurantCreateRequest.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/dto/RestaurantUpdateRequest.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/service/RestaurantCommandService.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/aggregate/Restaurant.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/repository/RestaurantRepository.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/infrastructure/repository/JpaRestaurantRepository.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/mapper/RestaurantMapper.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
matzipback/src/main/resources/application.yml

🌟개요
---
음식점 CUD 추가
🌐연결된 Issues
---
#41 #42 #43
📋작업사항
---
음식점 CUD 추가
---
음식점 부분 스웨거 태그 삽입
스웨거 정렬 기능 메소드 정렬로 활성화
✅체크리스트
---

feat: 음식점 CUD 추가

---

matzipback/src/main/java/com/matzip/matzipback/config/SwaggerConfig.java

🌟개요
---
스웨거 커스텀 로그인 필터 활성화
🌐연결된 Issues
---
#195 
📋작업사항
---
---
✅체크리스트
---

feat: 스웨거에 커스텀 로그인 필터 활성화

---

matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/service/ActiveLevelService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/repository/UserActiveLevelRepository.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/ActiveLevelDomainService.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/MessageQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/MessageMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/MessageQueryService.java
matzipback/src/main/resources/mappers/messageMappers/MessageMapper.xml

Reverts taste-house/mat_zip#198

Revert "feat: 쪽지방 목록 조회 기능"

---

matzipback/src/main/java/com/matzip/matzipback/exception/CustomExceptionHandler.java
matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
matzipback/src/main/java/com/matzip/matzipback/exception/ErrorResponse.java
matzipback/src/main/java/com/matzip/matzipback/exception/RestApiException.java

🌟개요
---
예외 처리 샘플 구조
🌐연결된 Issues
---
#214 
📋작업사항
---
- 커스텀 예외 추가
- Enum 타입으로 상태 코드, 메시지를 담는 타입 만듬
- 에외 응답 메시지 클래스 추가
---
✅체크리스트
---

feat: 예외 처리 샘플 구조

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PopularTagResponse.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml

🌟개요
---
각 게시판 카테고리 별 인기 태그 조회 기능
(태그 사용 빈도 높은 순으로 10개까지 현시되도록 구현)
🌐연결된 Issues
---
#216 
📋작업사항
---
인기 태그 조회 기능 구현
---
게시글 수정이 정상적으로 수행되었을 시 상태코드 204번이 반환되도록 수정
✅체크리스트
---

feat: 인기 태그 조회 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
matzipback/src/main/java/com/matzip/matzipback/exception/ValidErrorResponse.java

🌟개요
---
유효성 관련 글로벌 예외 처리 핸들러 수정
🌐연결된 Issues
---
#223 
📋작업사항
---
MethodArgumentNotValidException 에 대한 처리 핸들러 수정
---
✅체크리스트
---

refactoring: 유효성관련 글로벌 예외 핸들러 수정

---

matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessResMessage.java

🌟개요
---
성공 메시지 구현
🌐연결된 Issues
---
#219 
📋작업사항
---
성공 메시지 구현
- SuccessCode에 원하는 새로운 메시지를 넣어도 됩니다!
---
✅체크리스트
---

refactoring: 성공 메시지 enum 으로 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/PostAndTagRequestDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/TagDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Tag.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/TagRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/TagInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java

🌟개요
---
게시글, 태그 등록 기능 코드 리팩토링
🌐연결된 Issues
---
#228 
📋작업사항
---
게시글, 태그 등록 기능 코드 리팩토링
(사용자가 게시글 내 작성한 태그를 중복 확인 후 tags 테이블에 저장,
post_tag 테이블에 post_seq와 tag_seq를 저장,
게시글에 동일 태그를 반복해서 작성하는 경우 중복 확인을 통해 한번만 저장)
✅체크리스트
---

refactoring: 게시글, 태그 등록 기능 코드 리팩토링

---

matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostLikeInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostDTO.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java

🌟개요
---
게시글 좋아요 코드 리팩토링
🌐연결된 Issues
---
#226 
📋작업사항
---
- 서비스 계층에서 사용하는 데이터를 엔티티를 사용하지 않도록 처리
- modelMapper는 도메인 계층에서 사용하도록 처리
- 코드 간소화
✅체크리스트
---

refactoring: 게시글 좋아요 코드 리팩토링

---

matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/PostLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/PostLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/PostLikeInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/query/dto/LikedPostDTO.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java

🌟개요
---
리스트 좋아요 기능 코드 리팩토링
🌐연결된 Issues
---
#232 
📋작업사항
---
- 컨트롤러, 서비스 계층에서 Entity로 데이터 교환하는 코드 제거
- 불필요한 코드 간소화
- 요청 DTO valid 메세지 추가
✅체크리스트
---

refactoring: 리스트 좋아요 기능 코드 리팩토링

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ListCmtLikeReqDTO.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListCmtLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ListLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListCmtLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ListLikeRepository.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListCmtLikeDomainService.java
matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ListLikeDomainService.java

🌟개요
---
리스트 댓글 좋아요 기능 리팩토링
🌐연결된 Issues
---
#234 
📋작업사항
---
- 리스트 댓글 좋아요 리팩토링
- 컨트롤러, 서비스 계층에서 엔티티로 데이터 이동 제거
- 불필요한 코드 간소화
- 사용하지 않는 import 제거
---
✅체크리스트
---

refactoring: 리스트 댓글 좋아요 기능 리팩토링

---

matzipback/build.gradle
matzipback/src/main/java/com/matzip/matzipback/common/util/FileUploadUtils.java
matzipback/src/main/java/com/matzip/matzipback/config/MultipartJackson2HttpMessageConverter.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/service/RestaurantCommandService.java
matzipback/src/main/java/com/matzip/matzipback/restaurant/command/domain/aggregate/Restaurant.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewCreateRequest.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewImageRequest.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/service/ReivewCommandService.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/ReviewImage.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewImageRepository.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
matzipback/src/main/java/com/matzip/matzipback/review/command/infrastructure/repository/JpaReviewImageRepository.java
matzipback/src/main/java/com/matzip/matzipback/review/command/infrastructure/repository/JpaReviewRepository.java
matzipback/src/main/java/com/matzip/matzipback/review/command/mapper/ReviewMapper.java
matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/service/UserActivityDomainService.java
matzipback/src/main/resources/application.yml
matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml

🌟개요
---
리뷰 작성 기능 추가
🌐연결된 Issues
---
#10
📋작업사항
---
리뷰 작성 기능 추가
이미지 업로드 시 스웨어 문제로 맞지 않는 형식 수정
---
리뷰 조회 부분 스웨거 태그 어노테이션 삽입
포인트 조정 메소드가 point와 함께 userseq도 받도록 변경
리뷰 작성 시 음식점 별점 수정 및 회원 포인트 변경 추가
✅체크리스트
---

feat: 리뷰 작성 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml

🌟개요
---
게시글 내 태그 작성 시 관련 인기 태그 제시 기능 구현 
🌐연결된 Issues
---
#245
📋작업사항
---
게시글 등록 페이지에서 태그 작성 시 관련 인기 태그(키워드) 제시.
태그 등록을 위해 작성한 단어를 포함하면서, 게시판 전체에서 게시글에 가장 많이 등록된 태그 상위 10개까지 나타냄
---
End Point 수정
✅체크리스트
---

feat:  인기 태그 제시 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/PostAndTagRequestDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java

🌟개요
---
게시글 등록, 삭제 시 회원 활동포인트 업데이트 기능 구현
🌐연결된 Issues
---
#256
📋작업사항
---
게시글 등록, 삭제 시 회원 활동포인트 업데이트
---
게시글과 관련된 예외 처리 기능, 유효성 검사 코드 추가
✅체크리스트
---

feat: 게시글 등록, 삭제 시 회원 활동포인트 업데이트

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/ListBoxUpdateRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListBoxCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/repository/ListDomainRepository.java

🌟개요
리스트 서랍 수정 기능 구현
🌐연결된 Issues
#21 
📋작업사항
서랍 수정 했을때 리스트의 우선순위가 자동 조정되는 로직을 구현했습니다.
---
✅체크리스트
---

feat: #21 리스트 서랍 수정 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/dto/ReviewUpdateRequest.java
matzipback/src/main/java/com/matzip/matzipback/review/command/application/service/ReviewCommandService.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml

🌟개요
---
리뷰 수정, 삭제 기능 추가
🌐연결된 Issues
---
#11 #12 
📋작업사항
---
리뷰 수정 기능 추가
리뷰 삭제 기능 추가
---
http 422 상태코드 추가
리뷰 서비스 클래스명 오타 수정
리뷰 별점 수정 시 동기화되는 음식점 별점을 활성화된 리뷰에서만 통계내도록 수정
✅체크리스트
---

feat: 리뷰 수정, 삭제 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/EmailController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersCommandController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/dto/EmailSendRequest.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/OtherUserInfoDto.java
matzipback/src/main/java/com/matzip/matzipback/users/query/dto/userInfo/UserDetailInfoDTO.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersInfoMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/mapper/UsersMapper.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersInfoService.java
matzipback/src/main/java/com/matzip/matzipback/users/query/service/UsersQueryService.java
matzipback/src/main/resources/mappers/usersMappers/UserListMapper.xml

🌟개요
---
Swagger 관리를 위한 컨트롤러 수정
회원 상세조회 구현
🌐연결된 Issues
---
#78 
#76 
📋작업사항
---
이메일컨트롤러, 회원관리컨트롤러, 회원조회컨트롤러에 @Tag와 @Operation 추가
관리자의 회원상세조회, 회원 자신의 정보 상세조회, 다른 회원의 정보 상세조회
---
✅체크리스트
---

refactoring: Swagger 관리를 위한 컨트롤러 수정 +  feat: 회원상세조회

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCollectCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/MatzipQueryController.java

🌟개요
리스트 스웨거 어노테이션 수정
🌐연결된 Issues
#269 
📋작업사항
리스트 스웨거 어노테이션 수정 -> List 로 정리
---
✅체크리스트
---

chore: 리스트 스웨거 어노테이션 수정

---

matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewByRestaurantDTO.java
matzipback/src/main/java/com/matzip/matzipback/review/query/dto/ReviewByRestaurantResponse.java
matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml

🌟개요
---
음식점 별 리뷰 조회 추가
🌐연결된 Issues
---
#181
📋작업사항
---
음식점 별 리뷰 조회 추가
---
✅체크리스트
---

feat: 음식점 별 리뷰 조회 추가

---

matzipback/src/main/resources/application.yml

🌟개요
---
yaml파일 수정(비밀키 분리, 스웨거 탭 닫은 상태로 시작)
🌐연결된 Issues
---
#140
📋작업사항
---
비밀키 분리
---
스웨거 탭 닫은 상태로 시작
✅체크리스트
---

feat: yaml파일 수정(비밀키 분리, 스웨거 탭 닫은 상태로 시작)

---

matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReasonDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportDetailResponse.java
matzipback/src/main/java/com/matzip/matzipback/report/query/dto/ReportListResponse.java
matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
matzipback/src/main/resources/mappers/reportMappers/ReportMapper.xml

🌟개요
---
신고 검색 및 조회, 상세조회 기능 추가
🌐연결된 Issues
---
#81 #82 #83 
📋작업사항
---
신고 검색 및 조회
신고 상세조회
---
✅체크리스트
---

feat: 신고 검색 및 조회, 상세조회 기능 추가

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListBoxCommandService.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java

🌟개요
userSeq 수정
🌐연결된 Issues
#273 
📋작업사항
하드 코딩 제거
---
✅체크리스트
---

chore: #273 userSeq 수정

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListRequest.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequest.java
matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandServiceTest.java

🌟개요
리스트 등록, 수정, 삭제 테스트 코드 구현
🌐연결된 Issues
#275 
📋작업사항
리스트 등록, 수정, 삭제 테스트 코드 구현
---
✅체크리스트
---

test: #275 리스트 등록, 수정, 삭제 테스트 코드 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListCmtRequset.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/ListCmtCommandServiceTest.java

🌟개요
리스트 댓글 등록, 수정, 삭제 테스트 코드 구현
🌐연결된 Issues
#278 
📋작업사항
리스트 댓글 등록, 수정, 삭제 테스트 코드 구현
---
✅체크리스트
---

test: #278 리스트 댓글 등록, 수정, 삭제 테스트 코드 구현

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteMatzipRequest.java
matzipback/src/test/java/com/matzip/matzipback/matzipList/command/application/service/MatzipCommandServiceTest.java

🌟개요
리스트 맛집 등록, 수정, 삭제 테스트 코드 구현
🌐연결된 Issues
#282
📋작업사항
리스트 맛집 등록, 수정, 삭제 테스트 코드 구현
---
✅체크리스트
---

test: #282 리스트 맛집 등록, 수정, 삭제 테스트 코드 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/ReqPostCmtUpdateDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/PostCommentDomainService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/PostCommentInfraRepository.java
matzipback/src/test/java/com/matzip/matzipback/board/command/application/service/PostCommentServiceTest.java

🌟개요
---
댓글 CUD 기능에 대한 테스트
🌐연결된 Issues
---
#280 
📋작업사항
---
댓글 CUD 기능에 대한 테스트 코드 작성 및 테스트 진행
---
✅체크리스트
---

test: 댓글 CUD 기능에 대한 테스트 코드 작성 및 테스트 확인

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeService.java
matzipback/src/test/java/com/matzip/matzipback/board/query/service/PostCmtQueryServiceTest.java

🌟개요
---
회원 본인이 작성한 댓글 조회 테스트
🌐연결된 Issues
---
#286 
📋작업사항
---
회원 본인이 작성한 댓글 조회 기능 테스트 코드 작성 및 확인
---
✅체크리스트
---

test: 회원 본인이 작성한 댓글 조회 기능 테스트

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/Post.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/PostComment.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyList.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/aggregate/MyListComment.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/PenaltyCommandController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Penalty.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportView.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/PenaltyRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportViewRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PenaltyUpdateRequest.java
matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ReportAndPenaltyDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/PenaltyInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportViewInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
matzipback/src/main/java/com/matzip/matzipback/users/command/domain/aggregate/Users.java
matzipback/src/test/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandServiceTest.java

🌟개요
---
패널티 등록, 수정, 철회 기능 구현
🌐연결된 Issues
---
#86 
#87 
📋작업사항
---
패널티 등록, 수정, 철회 기능 구현
---
패널티 등록 수정 테스트 코드 작성
✅체크리스트
---

feat: 패널티 등록, 수정, 철회 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/PostCmtLikeReqDTO.java
matzipback/src/test/java/com/matzip/matzipback/like/command/application/service/PostCmtLikeServiceTest.java

🌟개요
---
게시물 댓글 좋아요/좋아요 취소 기능 테스트
🌐연결된 Issues
---
#284 
📋작업사항
---
게시물 댓글 좋아요/좋아요 취소 기능 테스트 코드 작성 및 확인
---
로직에 불필요한 DTO내 필드 값 및 코드 삭제
✅체크리스트
---

test: 게시물 댓글 좋아요/좋아요 취소 테스트 코드 작성 및 확인

---

matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersAuthController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersInfoController.java

🌟개요
---
로그아웃 구현 및 유저 정보/권한 컨트롤러 분리
🌐연결된 Issues
---
#73 
📋작업사항
---
로그아웃 요청 (프론트에서 처리 위해 요청만 보냄)
유저 정보 권한 컨트롤러 분리를 위한 클래스 이름 변경과 생성
---
✅체크리스트
---

feat: 로그아웃 구현

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java

🌟개요
---
게시글 댓글 기능 스웨거 테스트를 위한 설정
🌐연결된 Issues
---
#290 
📋작업사항
---
게시글 댓글 기능 스웨거 테스트를 위한 설정
---
✅체크리스트
---

chore: 게시글 댓글 기능 스웨거 테스트를 위한 설정

---

matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersAuthController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersInfoController.java

🌟개요
스웨거 설정을 위한 어노테이션 추가 및 안쓰는코드 삭제
🌐연결된 Issues
---
📋작업사항
---
---
✅체크리스트
---

chore: 스웨거 설정을 위한 어노테이션 추가 및 안쓰는코드 삭제

---

matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
matzipback/src/main/resources/mappers/boardMappers/PostCmtMapper.xml

🌟개요
---
결과 값 이상으로 인해 DTO 및 쿼리문 수정
🌐연결된 Issues
---
#294 
📋작업사항
---
DTO 필드 수정
매퍼 쿼리문 수정
---
✅체크리스트
---

chore: 게시물 댓글 조회 DTO 및 쿼리문 수정

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/ActiveLevelController.java
matzipback/src/main/java/com/matzip/matzipback/users/command/application/controller/UsersFollowController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/ActiveLevelQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersActivityQueryController.java
matzipback/src/main/java/com/matzip/matzipback/users/query/controller/UsersFollowQueryController.java

🌟개요
---
Swagger Tag 수정
🌐연결된 Issues
---
📋작업사항
---
Swagger Tag 수정
✅체크리스트
---

chore: Swagger Tag 수정

---

matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java

🌟개요
리스트 댓글 어노테이션 수정
🌐연결된 Issues
---
📋작업사항
리스트 댓글 어노테이션 수정
---
✅체크리스트
---

chore: 리스트 댓글 어노테이션 수정

---

README.md

🌟개요
---
readme 게시물 댓글 조회 테스트 추가
🌐연결된 Issues
---
#300 
📋작업사항
---
readme 게시물 댓글 조회 테스트 추가
---
✅체크리스트
---

docs: readme 게시물 댓글 조회 테스트 추가

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/BoardLikeDTO.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/board/command/domain/service/BoardDomainService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/BoardInfraRepository.java

🌟개요
---
게시판 즐겨찾기 등록, 취소 기능 구현
🌐연결된 Issues
---
#304 
📋작업사항
---
- 게시판 즐겨찾기 등록, 취소
---
✅체크리스트
---

feat: 게시판 즐겨찾기 등록, 취소 기능 구현

---

README.md

🌟개요
---
🌐연결된 Issues
---
📋작업사항
---
---
✅체크리스트
---

list 파트 리드미 수정

---

matzipback/src/main/resources/mappers/usersMappers/UserListMapper.xml

🌟개요
---
🌐연결된 Issues
#76 
📋작업사항
쿼리 수정
---
✅체크리스트
---

fix: 관리자 검색용 쿼리 수정(테스트를 위해 바꾼 코드가 문제가 됨)

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommentService.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
matzipback/src/main/java/com/matzip/matzipback/exception/CustomExceptionHandler.java
matzipback/src/main/java/com/matzip/matzipback/exception/GlobalExceptionHandler.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/PostLikeService.java
matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostCmtService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java

🌟개요
---
유저 인가 기능 추가
🌐연결된 Issues
---
#307 
📋작업사항
---
- 유저 인가 기능 추가
- 기능 리팩토링
---
✅체크리스트
---

refactoring: 유저 인가 기능 추가

---

README.md

🌟개요
---
🌐연결된 Issues
--- #318 
📋작업사항
---
---
✅체크리스트
---

docs: readme api 설계문서 추가

---

README.md
assets/api-docs/Swagger UI.mhtml

🌟개요
---
🌐연결된 Issues
---
📋작업사항
---
---
✅체크리스트
---

docs: readme 수정

---

matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessResMessage.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessSearchResMessage.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/dto/UserTokenDTO.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/CustomUserDetailService.java
matzipback/src/main/java/com/matzip/matzipback/sercurity/util/UserFeignClient.java
matzipuser/src/main/java/com/matzip/matzipuser/responsemessage/SuccessResMessage.java
matzipuser/src/main/java/com/matzip/matzipuser/responsemessage/SuccessSearchResMessage.java

🌟개요
---
msa 오류 수정
🌐연결된 Issues
---
#329 
📋작업사항
---
msa 오류 수정
- 파싱 오류 해결
---
✅체크리스트
---

fix: msa 오류 수정

---

matzipback/src/main/java/com/matzip/matzipback/message/query/controller/MessageQueryController.java
matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageShortDTO.java
matzipback/src/main/java/com/matzip/matzipback/message/query/mapper/MessageMapper.java
matzipback/src/main/java/com/matzip/matzipback/message/query/service/MessageQueryService.java
matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml

🌟개요
---
쪽지방 목록 조회 구현
🌐연결된 Issues
---
#335 
📋작업사항
---
- 쪽지방 목록 조회 구현
- mapper 로 구현
- mybatis 로 구현
- 쪽지방에서의 가장 마지막 쪽지를 들고오는 로직으로 구현
---
✅체크리스트
---

feat: 쪽지방 목록 조회 구현

---

matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/EmailController.java

🌟개요
---
EmailController 재 푸시
🌐연결된 Issues
---
📋작업사항
---
EmailController 누락돼서 재 푸시
---
✅체크리스트
---

refactoring: EmailController 누락 재 푸시

---

matzipback/src/main/java/com/matzip/matzipback/message/command/application/controller/MessageController.java
matzipback/src/main/java/com/matzip/matzipback/message/command/application/service/MessageService.java
matzipback/src/main/java/com/matzip/matzipback/message/command/domain/aggregate/Messages.java
matzipback/src/main/java/com/matzip/matzipback/message/command/domain/repository/MessageDomainRepository.java
matzipback/src/main/java/com/matzip/matzipback/message/command/domain/service/MessageDomainService.java
matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageDetailDTO.java
matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml

🌟개요
---
쪽지 삭제 기능 구현
🌐연결된 Issues
---
#340 
📋작업사항
---
- 쪽지 삭제 기능 구현
- command 디렉토리에 구현
- 로그인한 사용자와 url의 사용자 고유번호가 같은지 확인
- 로그인한 유저가 쪽지를 보낸 사람인지, 쪽지를 받는 사람인지에 따라 변경되는 컬럼 구분함
---
- 쪽지방 상세 조회에서 가져올 컬럼 수정 (고유번호도 같이 들고 오게함)
✅체크리스트
---

feat: 쪽지 삭제 기능 구현

---

matzipback/src/main/java/com/matzip/matzipback/exception/ErrorCode.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportMessageController.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportMessageService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportRepository.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/DomainReportMessageService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
matzipback/src/main/java/com/matzip/matzipback/report/command/dto/SaveMessageReportDTO.java
matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportInfraRepository.java
matzipback/src/main/java/com/matzip/matzipback/responsemessage/SuccessCode.java

🌟개요
---
쪽지 신고 기능 구현
🌐연결된 Issues
---
#343 
📋작업사항
---
- 쪽지 신고 기능 구현
---
✅체크리스트
---

feat: 쪽지 신고 기능 구현
